# Generated by Django 4.1.5 on 2023-02-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
