# Generated by Django 4.1.5 on 2023-02-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_bot', '0003_testresponse_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresponse',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
