# Generated by Django 4.1.5 on 2023-02-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_bot', '0004_alter_testresponse_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresponse',
            name='message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
