# Generated by Django 4.1.5 on 2023-02-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_bot', '0006_remove_testresponse_message_testresponse_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresponse',
            name='group',
        ),
    ]
