# Generated by Django 4.1.5 on 2023-02-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_bot', '0007_remove_testresponse_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresponse',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='edu_bot.group'),
            preserve_default=False,
        ),
    ]
