# Generated by Django 4.1.5 on 2023-02-08 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_bot', '0013_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
