# Generated by Django 4.1.5 on 2023-02-08 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_bot', '0016_group_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
    ]
