# Generated by Django 4.1.5 on 2023-02-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_bot', '0018_group_teacher_delete_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresponse',
            name='name',
        ),
        migrations.AddField(
            model_name='testresponse',
            name='answer_message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
