# Generated by Django 4.1.6 on 2023-02-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_bot', '0020_alter_testresponse_answer_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='test',
            name='group',
        ),
        migrations.RemoveField(
            model_name='test',
            name='message',
        ),
        migrations.RemoveField(
            model_name='test',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TestKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_bot.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_bot.teacher')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_bot.test')),
            ],
        ),
    ]
