# Generated by Django 4.1.6 on 2023-02-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_bot', '0021_remove_test_created_at_remove_test_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='login',
        ),
    ]
