# Generated by Django 4.1.6 on 2023-02-19 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_bot', '0022_remove_student_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testkeys',
            name='test',
        ),
        migrations.AddField(
            model_name='testkeys',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_bot.testkeys'),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
