# Generated by Django 4.1.6 on 2023-02-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_bot', '0023_remove_testkeys_test_testkeys_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
